- name: Install DevOps tools globally
  ansible.builtin.apt:
    name:
      - tmux
      - vim
#      - bastet #tetris
    state: present
  become: yes  # This will prompt for your local sudo password

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository for Ubuntu
  ansible.builtin.apt_repository:
    # 'ansible_distribution_release' automatically detects 'noble', 'jammy', etc.
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker Engine
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present