- name: Configure Local Admin VM
  hosts: localhost
  connection: local
  tasks:
    - name: Install DevOps tools locally
      ansible.builtin.apt:
        name:
          - tmux
          - vim
        state: present
      become: yes  # This will prompt for your local sudo password

#     - name: Create local directory structure for Super Lab
#       ansible.builtin.file:
#         path: "/home/user/linode/linux-svr/{{ item }}"
#         state: directory
#       loop:
#         # - assets/keys
#         # - assets/scripts
#         # - terraform
# #        - ansible