# assets/configs/nginx.conf

user  nginx;
worker_processes  1;  # Keep CPU/RAM usage low for the lab

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Optimization Handshake: Sendfile is faster for serving assets
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        # The location of your HTML
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # Custom 404 Handshake
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}